### ISSUE TITLE
[Android] It is possible to build as a lib?

### ISSUE THREAD

**Issue by CingKong** [devbean/QtCipherSqlitePlugin#12]

**Comment by CingKong** [comment]
Actually, I should say this: "How to use the library if i build it as a lib on android?"

**Comment by CingKong** [comment]
it seems the library isnt ready for usage on android at all?
I tried several ways to build&use it on android, but all failed.

**Comment by scienceasdf** [comment]
I succeed in building it with Android. Use the android toolkit, build it with qmake and you will get .so file. Copy the file into the plugin folder, and connection to a database is really easy.

**Comment by CingKong** [comment]
could you give me same details about the building procedure?
im not that familiar with android development.

**Comment by scienceasdf** [comment]
You need to open the .pro file with Qt Creator. Then use your kits for Android building( if you have configured your Android kits). And just in release mode( in debug mode the .so file will be of no use) click the build icon( not the run icon), you will get a .so library in your build path in the android_build/libs folder. So your will find libsqlitecipher.so in this folder, and copy that to your Qt for Android plugin folder, then you can use it with no difference with the desktop plugin. And I wanna know that if you are Chinese?

**Comment by CingKong** [comment]
sorry for the late reply. i have been busy these weeks. 

actually i tried the method you explained, if i did it correctly? Qt just won't pack the .so file into apk
or maybe this is not the "Qt for Android plugin folder" you said:
`Qt\Qt5.10.0\5.10.0\android_armv7\plugins\sqldrivers`

for the question you asked: yes, im chinese, why? did i use some stupid english?

**Comment by CingKong** [comment]
oops, stupid i finally found the problem.
everytime i tried to build for android, i modified the .pro file to build it as a "lib", but not an "App"
so the .so file i got is totally wrong.

thanks for the promotion.
