### ISSUE TITLE
I got 25 errors building it in  Android

### ISSUE THREAD

**Issue by doblesantos** [devbean/QtCipherSqlitePlugin#17]
I am trying to build it with qtcreator  qt5.10.1 gcc4.9 jdk1.8 sdk26 ndk17 for android armv7 but i get 25 errors. in shatheer.c they all  related with u64 .
this is the error message " use of a undeclared identifier u64"

**Comment by doblesantos** [comment]
i solve it using the  version 0.7

**Comment by CingKong** [comment]
no need to downgrade
as for now (2/15 2019), two small changes in the master branch will make it work

1.  change [this line](https://github.com/devbean/QtCipherSqlitePlugin/blob/master/sqlitecipher/sqlite3/shathree.c#L34), make it pass
2. get a new name for [B0](https://github.com/devbean/QtCipherSqlitePlugin/blob/master/sqlitecipher/sqlite3/shathree.c#L83) here, i guess something else somewhere has naming conflict

tested building for android x86 on Qt 5.12.1, errors still generated, but they were about copying lib file into qt installation dir, so nothing matters
