### ISSUE TITLE
Not working on Windows 5.14.1

### ISSUE THREAD

**Issue by 4A47** [devbean/QtCipherSqlitePlugin#32]
Config: Using QtTest library 5.14.1, Qt 5.14.1 (x86_64-little_endian-llp64 shared (dynamic) release build; by GCC 7.3.0)
FAIL!  : TestSqliteCipher::initTestCase() 'QSqlDatabase::isDriverAvailable("SQLITECIPHER")' returned FALSE. (SQLITECIPHER driver not found.)
C:/Users/slevin/Desktop/QtCipherSqlitePlugin-master/test/main.cpp(20) : failure location
PASS   : TestSqliteCipher::cleanupTestCase()
Totals: 1 passed, 1 failed, 0 skipped, 0 blacklisted, 77ms
********* Finished testing of TestSqliteCipher *********

**Comment by Monsterovich** [comment]
Did you fix this?

**Comment by 4A47** [comment]
I changed to older version of qt

**Comment by Monsterovich** [comment]
>I changed to older version of qt
I can't switch to older qt.

**Comment by Monsterovich** [comment]
https://github.com/devbean/QtCipherSqlitePlugin/issues/33
