### ISSUE TITLE
best crypt options

### ISSUE THREAD

**Issue by vampiebar** [devbean/QtCipherSqlitePlugin#36]
What is the best algorithm for opening crypto db with this library?

is it strong enough crypt options in example?

      QSqlDatabase glbDB = QSqlDatabase::addDatabase("SQLITECIPHER");
      glbDB.setDatabaseName(__DB_FILE_PATH__);
      glbDB.setPassword("test");
      glbDB.setConnectOptions("QSQLITE_USE_CIPHER=sqlcipher; QSQLITE_ENABLE_REGEXP");
      if (!glbDB.open()) {
          qDebug() << "Can not open connection: " << glbDB.lastError().driverText();
          //exit("CONNECTION_FAILED");
      }

**Comment by devbean** [comment]
I think it depends, there is no BEST algorithm. But it says the chacha20 is best for mobile, well since SQLCipher prefer AES 256 Bit CBC (SHA1/SHA256/SHA512 HMAC), that's what he thinks best.
