### ISSUE TITLE
wxsqlite3 RC4 encryption  is not supported!!!

### ISSUE THREAD

**Issue by SunshineAng** [devbean/QtCipherSqlitePlugin#40]

**Comment by devbean** [comment]
The latest develop branch did support RC4 encryption. Please let me know if it works well.

**Comment by SunshineAng** [comment]
> 最新开发的分支确实支持RC4加密。请让我知道，如果它的工作原理良好。

**Comment by SunshineAng** [comment]
> The latest develop branch did support RC4 encryption. Please let me know if it works well.

I'm using Latest Release V1.2, but it doesn't work with RC4

**Comment by devbean** [comment]
Yes because v1.3 has not been released so you have to checkout develop branch. If there is no problem it'll get its own tag.
