### ISSUE TITLE
nullptr issue when imported into qt 5.5.1 mingw version

### ISSUE THREAD

**Issue by xeoshow** [devbean/QtCipherSqlitePlugin#7]
Hi,

I just tried to  imported into qt 5.5.1 (mingw version, but got below error when compiling, what is the problem and how should I do? Thanks!

C:\gitrepository\QtCipherSqlitePlugin-master\sqlitecipher\qsql_sqlite.cpp:666: error: 'nullptr' was not declared in this scope
     if (sqlite3_open_v2(db.toUtf8().constData(), &d->access, openMode, nullptr) == SQLITE_OK) {
                                                                        ^

**Comment by devbean** [comment]
Please check if your compiler supports C++11 nullptr feature. nullptr is a keyword of C++11.

**Comment by xeoshow** [comment]
I just import your project directly into QT, and qt 5.5.1 mingw version should support C++11

**Comment by devbean** [comment]
Hi, I noticed you have closed this issue. Did you solve your problem?

**Comment by xeoshow** [comment]
Adding below line resolved the issue. Since it is so fundamental issue, so closed directly. Thanks!

QMAKE_CXXFLAGS += -std=c++11
