### ISSUE TITLE
Any plan to support SQLCipher?

### ISSUE THREAD

**Issue by xeoshow** [devbean/QtCipherSqlitePlugin#8]
Hi,

This great project seems used wxsqlite3 for Cipher, Sqlcipher is a more popular SQLite extension that provides 256 bit AES encryption of database files. i am wondering whether there is a plan to support it.

Link for Sqlcipher :  
https://github.com/sqlcipher/sqlcipher

**Comment by devbean** [comment]
Yes i think so. If Cipher is more popular and the licences are OK, I think it could do that.

**Comment by xeoshow** [comment]
Great to hear that!
Indeed SQLCipher is more popular(1971 stars on github) and the license is commercial friendly.

**Comment by fro0m** [comment]
it seems that sqlcipher is better solution

**Comment by Swerved** [comment]
The issue with SQLCipher is it doesn't build on Windows. By design, actually by the looks of it -- they charge on their website for a DLL version.

Because of the pain even getting that to build, I've been using this plugin instead. Very happy with it :)

**Comment by devbean** [comment]
Please try version 1.0. I'll close this issue due to so long time.
