### ISSUE TITLE
iOS error

### ISSUE THREAD

**Issue by angeluslove** [devbean/QtCipherSqlitePlugin#9]
install -m 644 -p libsqlitecipher.a /Users/angeluslove/Qt5.8.0/5.8/ios/plugins/sqldrivers/libsqlitecipher.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s /Users/angeluslove/Qt5.8.0/5.8/ios/plugins/sqldrivers/libsqlitecipher.a

but :

Starting remote process.
("QSQLITE")
QSqlDatabase: SQLITECIPHER driver not loaded
QSqlDatabase: available drivers: QSQLITE
Can not open connection:  "Driver not loaded"
exited with exit code -1, 
Run ended.

**Comment by devbean** [comment]
Yes, I have noticed this problem and I'm working on it now. But I'm not so familiar with Qt plugins on iOS so it's a bit slow. I think this might because the plugin should be compiled with static link but not sure. If you found any solution, please let me know. Thank you!

**Comment by angeluslove** [comment]
Normal compilation libsqlitecipher.a

you app.pro
add    
ios:LIBS += -L$$PWD/ -lsqlitecipher.       //Compiled  libsqlitecipher.a directory address

you main.cpp
add
#include <QtPlugin>
Q_IMPORT_PLUGIN(SqliteCipherDriverPlugin)

iOS  test  Output results：
("SQLITECIPHER", "QSQLITE")
1 :  "AAA"
2 :  "BBB"
3 :  "CCC"
4 :  "DDD"
5 :  "EEE"
6 :  "FFF"
7 :  "GGG"
---------- 

1 :  "ZZZ"
2 :  "BBB"
3 :  "CCC"
4 :  "DDD"
5 :  "EEE"
6 :  "FFF"
7 :  "GGG"
---------- 

1 :  "ZZZ"
2 :  "BBB"
3 :  "CCC"
5 :  "EEE"
6 :  "FFF"
7 :  "GGG"
exited with exit code 0,

**Comment by devbean** [comment]
Thank you, I think this could do. I'll close this issue and add a wifi page for it. If there is any problem, please reopen it. Thanks again!
